name: saro
description: saro mobile app
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  go_router: ^13.0.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  dio: ^5.3.0
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  flutter_sliding_up_panel: ^2.1.1
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  intl: ^0.18.1
  socket_io_client: ^2.0.3+1
  bloc_concurrency: ^0.2.2
  flutter_holo_date_picker: ^1.1.3
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  http_parser: ^4.0.2
  timeago: ^3.6.0
  gif_view: ^0.4.0
  keyboard_actions: ^4.2.0
  firebase_messaging: ^14.7.6
  firebase_core: ^2.24.0
  awesome_notifications: ^0.8.2
  lottie: ^2.7.0
  flutter_spinkit: ^5.2.0
  audioplayers: ^5.2.1
  firebase_analytics: ^10.7.2
  badges: ^3.1.2
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2
  device_preview: ^1.1.0
  screenshot: ^2.1.0
  screen_capture_event: ^1.0.0+1
  dotted_line: ^3.2.2
  cached_video_player: ^2.0.4
  cached_network_svg_image: ^0.0.7
  flutter_stripe: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.1

flutter_gen:
  output: lib/resources/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/gif/
    - assets/animations/

  fonts:
    - family: Saro
      fonts:
        - asset: assets/fonts/saro_font.ttf
